version: '3'

services:
  app:
    container_name: evisitapp
    restart: always
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    links:
      - mongo
  
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"